import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Parser.Parser;
import compiler.Parser.Program;

import java.io.StringReader;
import java.io.IOException;

public class TestParser {
    public static void main(String[] args) {
        String source = "" +
                "fun main() {\n" +
                "  write(\"hello\");\n" +
                "}";

        try {
            StringReader reader = new StringReader(source);
            Lexer lexer = new Lexer(reader);
            Parser parser = new Parser(lexer);
            Program ast = parser.parseProgram();
            System.out.println("===== AST Generated by the Parser =====");
            System.out.println(ast);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
